version: '3.7'
volumes:
    database:
services:
    db:
        image: mysql:latest
        container_name: pw2-mysql
        ports:
            - 3306:3306
        volumes:
            - database:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=pw2
            - MYSQL_DATABASE=pw2
            - MYSQL_USER=pw2
            - MYSQL_PASSWORD=pw2
    phpMyAdmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: pw2-phpmyadmin
        environment:
            - PMA_ARBITRARY=1
        links:
            - db
        ports:
            - 80:80
        volumes:
            - /sessions
    wildfly:
        build: .
        container_name: pw2-wildfly
        ports:
            - 8080:8080
            - 9990:9990
        